version: "2"
services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./sql/model:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
